### ISSUE TITLE
How can I run the test_vps.py and eval_vpq.py program.I cant find the dataset "leftImg8bit_sequence.zip and gtFine.zip"

### ISSUE THREAD

**Issue by Eagle104fred** [mcahny/vps#14]
I cant find the datasets "leftImg8bit_sequence.zip and gtFine.zip" in cityscapes dataset.When I run the test program wil got such error like this:/home/eagle/work/vps-master/tools/config/config.py:180: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  exp_config = edict(yaml.load(f))
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
==> Inside PanopticFuseTrack (Device ID: 0)
--- Load flow module: /home/eagle/work/vps-master/work_dirs/flownet/FlowNet2_checkpoint.pth.tar
[                                                  ] 0/1500, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/test_vpq.py", line 209, in <module>
    main()
  File "tools/test_vpq.py", line 158, in main
    data_loader)
  File "tools/test_vpq.py", line 42, in single_gpu_test
    for i, data in enumerate(data_loader):
  File "/home/eagle/anaconda3/envs/vps/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/eagle/anaconda3/envs/vps/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/eagle/anaconda3/envs/vps/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/eagle/anaconda3/envs/vps/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/eagle/anaconda3/envs/vps/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/eagle/anaconda3/envs/vps/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/eagle/anaconda3/envs/vps/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/eagle/work/vps-master/mmdet/datasets/custom.py", line 140, in __getitem__
    return self.prepare_test_img(idx)
  File "/home/eagle/work/vps-master/mmdet/datasets/cityscapes_vps.py", line 148, in prepare_test_img
    return self.pipeline(results)
  File "/home/eagle/work/vps-master/mmdet/datasets/pipelines/compose.py", line 22, in __call__
    data = t(data)
  File "/home/eagle/work/vps-master/mmdet/datasets/pipelines/loading.py", line 49, in __call__
    img = mmcv.imread(filename)
  File "/home/eagle/anaconda3/envs/vps/lib/python3.7/site-packages/mmcv/image/io.py", line 41, in imread
    'img file does not exist: {}'.format(img_or_path))
  File "/home/eagle/anaconda3/envs/vps/lib/python3.7/site-packages/mmcv/utils/path.py", line 32, in check_file_exist
    raise FileNotFoundError(msg_tmpl.format(filename))
FileNotFoundError: img file does not exist: data/cityscapes_vps/val/img_all/frankfurt_000000_001732_leftImg8bit.png

**Comment by mcahny** [comment]
The Cityscapes dataset (leftImg8bit_sequence.zip and gtFine.zip) can be found at https://www.cityscapes-dataset.com/.
