### ISSUE TITLE
Training error on cityscapes-vps

### ISSUE THREAD

**Issue by KevinGrantLee** [mcahny/vps#7]
Hello,

I've encountered a bug when trying to train the network and am wondering if anyone else has encountered a similar issue or has some insight.

So I run this command
`python ./tools/train.py configs/cityscapes/fusetrack.py --gpus 4`
(I also get the same error with 3 gpus)

I've run the command multiple times, and I get the following error at different iterations (different training samples) each time:
`Traceback (most recent call last):
  File "./tools/train.py", line 108, in <module>
    main()
  File "./tools/train.py", line 104, in main
    logger=logger)
  File "/vps/mmdet/apis/train.py", line 90, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/vps/mmdet/apis/train.py", line 257, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/runner.py", line 264, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/vps/mmdet/apis/train.py", line 68, in batch_processor
    losses = model(**data)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.gather(outputs, self.output_device)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 165, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 68, in gather
    res = gather_map(outputs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 60, in gather_map
    raise ValueError('All dicts must have the same number of keys')
`

This is the last line before the error propagates into the pytorch code.
`  File "/vps/mmdet/apis/train.py", line 68, in batch_processor
    losses = model(**data)`

I've already tried printing the number of keys of all dictionaries inside variable `data` but the number of keys doesn't vary across iterations. I've also tried rerunning the dataset preparation scripts.

Does anyone have any insight? Thanks!

**Comment by mcahny** [comment]
Can you try this command to check it works?
“bash ./tools/dist_train.sh configs/cityscapes/fusetrack.py ${GPU_NUM}”

**Comment by KevinGrantLee** [comment]
That solved my issue, thanks!
